DROP TABLE IF EXISTS memberships;
DROP TABLE IF EXISTS times;
DROP TABLE IF EXISTS bills;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS owners;
